### ISSUE TITLE
unicode error with python2.7

### ISSUE THREAD

**Issue by sherpya** [romanlv/trml2pdf#6]
`trml2pdf.py` uses text_type from `six` that transforms the text in `unicode` then passes `xml` to python minidom, on python 2 the parses is not able to handle unicode string, so it breaks the renderer if the xml contains non-ascii data

minidom on py2 needs decoded bytestream, so `_rml_flowable._textual` should return plain `rc`

**Comment by romanlv** [comment]
Until this issue is fixed (broken since 0.3 when python3 support was added),  use `trml2pdf==0.2` that works fine with unicode in Python 2

**Comment by romanlv** [comment]
should be fixed with #10
